<?php

namespace Tests\Feature;

use App\Models\Product;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProductsTest extends TestCase
{
    use RefreshDatabase;

    private $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = $user = User::factory()->create();
    }

    public function test_products_page_contains_empty_table(): void
    {
        $response = $this->actingAs($this->user)->get('/products');
        $response->assertSee('No products found.');
        $response->assertStatus(200);
    }

    public function test_products_page_contains_none_empty_table(): void
    {
        $product = Product::create([
            'name' => 'iPhone 13',
            'price' => '8789',
        ]);

        $response = $this->actingAs($this->user)->get('/products');
        $response->assertDontSee('No products found.');
        $view_products = $response->viewData('products');

        $this->assertEquals($product->name, $view_products->first()->name);
        $response->assertStatus(200);
    }

    public function test_can_not_see_11th_product(): void
    {
        $products = Product::factory(11)->create();

        $response = $this->actingAs($this->user)->get('/products');

        $response->assertDontSee($products->last()->name);
    }
}
